backend:
  name: github
  branch: master
  repo: samogray/test-gatsby

media_folder: src/images
public_folder: src/images

collections:
  - name: 'post'
    label: 'Posts'
    folder: 'src/articles'
    create: true
    slug: '{{slug}}'
    fields:
      - { label: 'Title', name: 'title', widget: 'string' }
      - { label: 'Date', name: 'date', widget: 'datetime' }
      - { label: 'Preview', name: 'image', widget: 'image' }
