backend:
  name: github
  branch: master
  repo: samogray/test-gatsby

media_folder: src/images
public_folder: src/images

collections:
  - name: 'team'
    label: 'Posts'
    folder: 'src/articles'
    create: true
    slug: '{{slug}}'
    fields:
      - { label: 'Team Member', name: 'title', widget: 'string' }
      - { label: 'Bio', name: 'bio', widget: 'markdown' }
